# -*- coding: utf-8 -*-

import sys
import unicodedata

from jamo import *

# Braille Pattern
define_unicode_vars(globals(), 0x2800, 0x283f, 'BRAILLE PATTERN ', 'BR_')

# Compatibility Jamo
define_unicode_vars(globals(), 0x3131, 0x3163, 'HANGUL LETTER ', 'COMPAT_')

def decompose(str):
    return unicodedata.normalize('NFD', str)

BASE_KOR_BRAILLE_TBL = {
    L_KIYEOK : BR_DOTS_4,
    L_SSANGKIYEOK : BR_DOTS_6 + BR_DOTS_4,
    L_NIEUN : BR_DOTS_14,
    L_TIKEUT : BR_DOTS_24,
    L_SSANGTIKEUT : BR_DOTS_6 + BR_DOTS_24,
    L_RIEUL : BR_DOTS_5,
    L_MIEUM : BR_DOTS_15,
    L_PIEUP : BR_DOTS_45,
    L_SSANGPIEUP : BR_DOTS_6 + BR_DOTS_45,
    L_SIOS : BR_DOTS_6,
    L_SSANGSIOS : BR_DOTS_6 + BR_DOTS_6,
    L_IEUNG : BR_DOTS_1245,
    L_CIEUC : BR_DOTS_46,
    L_SSANGCIEUC : BR_DOTS_6 + BR_DOTS_46,
    L_CHIEUCH : BR_DOTS_56,
    L_KHIEUKH : BR_DOTS_124,
    L_THIEUTH : BR_DOTS_125,
    L_PHIEUPH : BR_DOTS_145,
    L_HIEUH : BR_DOTS_245,

    V_A : BR_DOTS_126,
    V_AE : BR_DOTS_1235,
    V_YA : BR_DOTS_345,
    V_YAE : BR_DOTS_345 + BR_DOTS_1235,
    V_EO : BR_DOTS_234,
    V_E : BR_DOTS_1345,
    V_YEO : BR_DOTS_156,
    V_YE : BR_DOTS_34,
    V_O : BR_DOTS_136,
    V_WA : BR_DOTS_1236,
    V_WAE : BR_DOTS_1236 + BR_DOTS_1235,
    V_OE : BR_DOTS_13456,
    V_YO : BR_DOTS_346,
    V_U : BR_DOTS_134,
    V_WEO : BR_DOTS_1234,
    V_WE : BR_DOTS_1234 + BR_DOTS_1235,
    V_WI : BR_DOTS_134 + BR_DOTS_1235,
    V_YU : BR_DOTS_146,
    V_EU : BR_DOTS_246,
    V_YI : BR_DOTS_2456,
    V_I : BR_DOTS_135,

    T_KIYEOK : BR_DOTS_1,
    T_SSANGKIYEOK : BR_DOTS_1 + BR_DOTS_1,
    T_KIYEOK_SIOS : BR_DOTS_1 + BR_DOTS_3,
    T_NIEUN : BR_DOTS_25,
    T_NIEUN_CIEUC : BR_DOTS_25 + BR_DOTS_13,
    T_NIEUN_HIEUH : BR_DOTS_25 + BR_DOTS_356,
    T_TIKEUT : BR_DOTS_35,
    T_RIEUL : BR_DOTS_2,
    T_RIEUL_KIYEOK : BR_DOTS_2 + BR_DOTS_1,
    T_RIEUL_MIEUM : BR_DOTS_2 + BR_DOTS_26,
    T_RIEUL_PIEUP : BR_DOTS_2 + BR_DOTS_12,
    T_RIEUL_SIOS : BR_DOTS_2 + BR_DOTS_3,
    T_RIEUL_THIEUTH : BR_DOTS_2 + BR_DOTS_236,
    T_RIEUL_PHIEUPH : BR_DOTS_2 + BR_DOTS_256,
    T_RIEUL_HIEUH : BR_DOTS_2 + BR_DOTS_356,
    T_MIEUM : BR_DOTS_26,
    T_PIEUP : BR_DOTS_12,
    T_PIEUP_SIOS : BR_DOTS_12 + BR_DOTS_3,
    T_SIOS : BR_DOTS_3,
    T_SSANGSIOS : BR_DOTS_34,
    T_IEUNG : BR_DOTS_2356,
    T_CIEUC : BR_DOTS_13,
    T_CHIEUCH : BR_DOTS_23,
    T_KHIEUKH : BR_DOTS_235,
    T_THIEUTH : BR_DOTS_236,
    T_PHIEUPH : BR_DOTS_256,
    T_HIEUH : BR_DOTS_356,
    }

# Hangul Compatibility Jamo 에는 초성과 종성의 구분이 없다
COMPAT_TBL = {
    COMPAT_KIYEOK : BR_DOTS_4,
    COMPAT_SSANGKIYEOK : BR_DOTS_6 + BR_DOTS_4,
    COMPAT_NIEUN : BR_DOTS_14,
    COMPAT_TIKEUT : BR_DOTS_24,
    COMPAT_SSANGTIKEUT : BR_DOTS_6 + BR_DOTS_24,
    COMPAT_RIEUL : BR_DOTS_5,
    COMPAT_MIEUM : BR_DOTS_15,
    COMPAT_PIEUP : BR_DOTS_45,
    COMPAT_SSANGPIEUP : BR_DOTS_6 + BR_DOTS_45,
    COMPAT_SIOS : BR_DOTS_6,
    COMPAT_SSANGSIOS : BR_DOTS_6 + BR_DOTS_6,
    COMPAT_IEUNG : BR_DOTS_1245,
    COMPAT_CIEUC : BR_DOTS_46,
    COMPAT_SSANGCIEUC : BR_DOTS_6 + BR_DOTS_46,
    COMPAT_CHIEUCH : BR_DOTS_56,
    COMPAT_KHIEUKH : BR_DOTS_124,
    COMPAT_THIEUTH : BR_DOTS_125,
    COMPAT_PHIEUPH : BR_DOTS_145,
    COMPAT_HIEUH : BR_DOTS_245,

    COMPAT_A : BR_DOTS_126,
    COMPAT_AE : BR_DOTS_1235,
    COMPAT_YA : BR_DOTS_345,
    COMPAT_YAE : BR_DOTS_345 + BR_DOTS_1235,
    COMPAT_EO : BR_DOTS_234,
    COMPAT_E : BR_DOTS_1345,
    COMPAT_YEO : BR_DOTS_156,
    COMPAT_YE : BR_DOTS_34,
    COMPAT_O : BR_DOTS_136,
    COMPAT_WA : BR_DOTS_1236,
    COMPAT_WAE : BR_DOTS_1236 + BR_DOTS_1235,
    COMPAT_OE : BR_DOTS_13456,
    COMPAT_YO : BR_DOTS_346,
    COMPAT_U : BR_DOTS_134,
    COMPAT_WEO : BR_DOTS_1234,
    COMPAT_WE : BR_DOTS_1234 + BR_DOTS_1235,
    COMPAT_WI : BR_DOTS_134 + BR_DOTS_1235,
    COMPAT_YU : BR_DOTS_146,
    COMPAT_EU : BR_DOTS_246,
    COMPAT_YI : BR_DOTS_2456,
    COMPAT_I : BR_DOTS_135,

    COMPAT_KIYEOK_SIOS : BR_DOTS_1 + BR_DOTS_3,
    COMPAT_NIEUN_CIEUC : BR_DOTS_25 + BR_DOTS_13,
    COMPAT_NIEUN_HIEUH : BR_DOTS_25 + BR_DOTS_356,
    COMPAT_RIEUL_KIYEOK : BR_DOTS_2 + BR_DOTS_1,
    COMPAT_RIEUL_MIEUM : BR_DOTS_2 + BR_DOTS_26,
    COMPAT_RIEUL_PIEUP : BR_DOTS_2 + BR_DOTS_12,
    COMPAT_RIEUL_SIOS : BR_DOTS_2 + BR_DOTS_3,
    COMPAT_RIEUL_THIEUTH : BR_DOTS_2 + BR_DOTS_236,
    COMPAT_RIEUL_PHIEUPH : BR_DOTS_2 + BR_DOTS_256,
    COMPAT_RIEUL_HIEUH : BR_DOTS_2 + BR_DOTS_356,
    COMPAT_PIEUP_SIOS : BR_DOTS_12 + BR_DOTS_3,
    }

# 온표
BR_WHOLE_KO = BR_DOTS_123456
    

    
SIMPLE_KOR_BRAILLE_TBL = BASE_KOR_BRAILLE_TBL.copy()
SIMPLE_KOR_BRAILLE_TBL[L_IEUNG] = ''

def to_braille(str):
    str = decompose(str)
    res = ''
    for c in str:
        if c in SIMPLE_KOR_BRAILLE_TBL:
            res += SIMPLE_KOR_BRAILLE_TBL[c]
        else:
            res += c
    return res
            
while True:
    line = sys.stdin.readline()
    if not line:
        break
    line = to_braille(line)
    sys.stdout.write(line)
